const express                         = require('express');
const graphql                         = require('graphql'); //
const ejs                             = require('ejs'); 
const jsonwebtoken                    = require('jsonwebtoken'); //
const mongoose                        = require('mongoose'); 
const passport                        = require('passport'); 
const express_graphql                 = require('express-graphql');
const express_sessions                = require('express-session');
const body_parser                     = require('body-parser');
const helmet                          = require('helmet');
const xss                             = require('xss');
const dotenv                          = require('dotenv');
const morgan                          = require('morgan');
const passport_linkedin               = require('passport-linkedin'); // 
const passport_google_oauth20         = require('passport-google-oauth20'); //
const redis                           = require('redis');
const RedisStore                      = require('connect-redis')(express_sessions);
/////////////////////////////////////// GRAB CONFIG STUFF
const databaseConnection              = require('./Config/DatabaseConnection.js');
/////////////////////////////////////// GRAB AUTH STRATEGIES 
const strategies                      = require('./Passport/PassportAuthentication.js');
/////////////////////////////////////// GRAB MODELS
/////////////////////////////////////// GRAB CONTROLLERS
/////////////////////////////////////// GRAB MIDDLEWARES
/////////////////////////////////////// GRAB ROUTES
const authentication                  = require('./Routes/Authentication.js');
const questions                       = require('./Routes/Questions.js');
const responses                       = require('./Routes/Responses.js');
const pageRendering                   = require('./Routes/PageRenderingRoutes.js');


// Load .env
dotenv.config({ path: './Config/.env' });

// Init express && router
const app = express();

// Init View engine
app.set('view engine','ejs');

// Init database connection
const mongoDatabase = databaseConnection.mongodbConnection();

// Init redis connection
const redisDatabase = databaseConnection.redisConnection();

// Init sessions
app.use(express_sessions({
	secret : process.env.EXPRESS_SESSION_KEY,
	resave : false,
	saveUninitialized : true,
	store: new RedisStore({ host: process.env.REDIS_LABS_HOST, port: process.env.REDIS_LABS_PORT, client: redisDatabase }),
}))

// Init Passport
app.use(passport.initialize());
strategies.googleStrategy();
strategies.githubStrategy();
strategies.linkedInStrategy();
strategies.serializeUser();
// strategies.deserializeUser();

// Init graphql

// Init static folder to serve
app.use(express.static('Public/dist'));

// Init body parser
app.use(express.urlencoded({ extended: false }))
app.use(express.json());


const auth = require('./Middlewares/Authentication.js');
const validators = require('./Middlewares/Validators.js');
const nodemailer = require('nodemailer');

app.get('/get',/*validators.checkLanguage, auth.isAuthenticated,auth.isCompletedCredentiels,*/  async(req,res)=>{
	
	// Create transporter object with credentials
	var transporter = nodemailer.createTransport({
		service :'gmail',
		auth: {
			user: 'mouadtaoussi0@gmail.com', //generated by Mailtrap
			pass: 'vivewebdev0' //generated by Mailtrap
		}
	});

	// verify connection configuration
	transporter.verify(function(error, success) {
	  if (error) {
	    console.log(error);
	  } else {
	    console.log("Server is ready to take our messages");
	  }
	});
	// Create email options
	var mailOptions = {
		from: '"SurveyApp Team" <mouadtaoussi0@gmail.com>',
		to: 'mouadtaoussi0@gmail.com',
		subject: 'Reset password request',
	    text: 'Hey there, it’s your link to change your password below ;) ', 
	    html: `
		<!DOCTYPE html>
		<html>
		<head>
			<title>Email template</title>
		</head>
		<body style='background-color: rgba(0,0,0,.1);padding:20px;' >
			<center></center>
			<div style="width: 70%;margin: 20px auto;background: white;height: auto;color: rgba(0,0,0,.89);padding:20px;">Hello World<br>
			<a href='~'>
				<button style="border: 0;padding: 5px 30px 5px 30px;margin:20px 00px 0px 0px;font-family: 'Cabin', sans-serif;background-color: #1554a7;color: white;">Change Password</button>
			</a>
			</div>
			
			<center>
				<ul style="list-style: none;margin: 10px 10px 10px 10px;" class="footer-list local-mt-4">
					<li style='display: inline;padding:8px;' class='footer-list-item'>Terms of service</li>
					<li style='display: inline;padding:8px;' class='footer-list-item'>Privacy & policy</li>
					<li style='display: inline;padding:8px;' class='footer-list-item'>How it works?</li>
				</ul>
			</center>
		</body>
		</html>
	    `
	};
	// send it!
	transporter.sendMail(mailOptions, (error, info) => {
		
		if (error) {
			return {
				message : "Something went wrong!",
				sent : false
			}
			console.log('error')
		} else {
			return {
				message: "Email Sent To " + email,
				sent: true,
			};	
			console.log('sent')
		}
	});
	
	res.json(req.session);
})
app.get('/set',(req,res)=>{
	const local = {
		user : 225
	}
	req.session.userid=null;
	req.session.user = local;
	res.json(req.session)
})
app.get('/del',(req,res)=>{
	req.session.destroy(function(err) {
	  // cannot access session here
		res.json({'message':'session deleted'});
	})

})

// Routes
app.use('/auth',authentication);
app.use('/question',questions);
app.use('/response',responses);
app.use('/',pageRendering);

// INITiAL ROUTE
// app.get('/',(req,res)=>{
// 	res.render('pages/index');
// 	// redisDatabase.keys('*',  (err, keys)=>{
// 	// 	console.log(keys);
// 	// })
// 	redisDatabase.get('sess:mk8xcUI4epdpI80EYxz8g1ZkWDw09Pqm',  (err, value)=>{
// 		console.log(JSON.parse(value));
// 	})
// })

// Init helmet
app.use(helmet());

// Init xss
app.use(xss);

// Init logging
if (process.env.NODE_ENV === 'development') {
  app.use(morgan('dev'))
}


// Init port && Start the server
const PORT = process.env.PORT || process.env.NODE_PORT;
app.listen(PORT,()=>{
	console.log("[INFO]: Server up and running!")
});